name: fitquest
description: workout app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  camera: ^0.10.6
  path: ^1.9.0
  get: ^4.6.6
  dartz: ^0.10.1
  percent_indicator: ^4.2.2
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  path_provider: ^2.1.4
  flutter_bloc: ^9.0.0
  flutter_tts: ^4.2.2
  stream_d: ^0.3.0
  msh_checkbox: ^2.0.1
  firebase_messaging: ^15.2.1
  synchronized: ^3.3.0+3
  sliding_up_panel: ^2.0.0+1
  intl: ^0.20.2
  #syncfusion_flutter_charts: ^29.1.35
  table_calendar: ^3.2.0
  video_player: ^2.9.5
  cloud_functions: ^5.3.1
  get_it: ^8.0.3
  #agora_uikit: ^1.3.10



  cloud_firestore: ^5.6.1




  google_mlkit_commons: any
  google_mlkit_pose_detection: ^0.14.0




dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/im/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/im/
    - assets/videos/

